// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vOfsEqyiGwSNryuCipyqiFL22lpCPRs',
    appId: '1:771741804521:web:301f8a02bc3236f9da4d78',
    messagingSenderId: '771741804521',
    projectId: 'cinestream-e3446',
    authDomain: 'cinestream-e3446.firebaseapp.com',
    storageBucket: 'cinestream-e3446.appspot.com',
    measurementId: 'G-0V8KXQ5S5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFU9WVl25dzWsZpiNYAkSYioTGi__0pJc',
    appId: '1:771741804521:android:d7d5df1ccf12e939da4d78',
    messagingSenderId: '771741804521',
    projectId: 'cinestream-e3446',
    storageBucket: 'cinestream-e3446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl59XG31ifNbEkl139e_wwGmbbK09Jg_U',
    appId: '1:771741804521:ios:968ec1d207c72413da4d78',
    messagingSenderId: '771741804521',
    projectId: 'cinestream-e3446',
    storageBucket: 'cinestream-e3446.appspot.com',
    iosBundleId: 'com.example.cinestream',
  );
}
